version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: mocking_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - HT_MODE=REPLAY

